uiContainer:
  image: twobrowin/boxed-bots-ui:2.4.2
  imagePullPolicy: IfNotPresent
  containerPort: 8080

botContainer:
  image: twobrowin/boxed-bots-bot:2.4.2
  imagePullPolicy: IfNotPresent

containers:
  env:
  - name: TZ
    value: Europe/Moscow
  
  - name: PATH_SECURE
    value: "true"
  - name: PATH_PREFIX
    value: 

  - name: TG_TOKEN
    valueFrom:
      secretKeyRef:
        name: dev-ops-it-2025
        key: tg_token

  - name: POSTGRES_HOST
    value: postgres.boxed-bots.ru:5432
  - name: POSTGRES_DB
    value: dev-ops-it-2025
  - name: POSTGRES_USER
    value: dev-ops-it-2025
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dev-ops-it-2025
        key: postgres_password

  - name: MINIO_HOST
    value: minio.boxed-bots.ru
  - name: MINIO_SECURE
    value: "true"
  - name: MINIO_ACCESS_KEY
    value: dev-ops-it-2025
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: dev-ops-it-2025
        key: minio_secret_key

  - name: KEYCLOAK_URL
    value: https://keycloak.boxed-bots.ru
  - name: KEYCLOAK_REALM
    value: master
  - name: KEYCLOAK_CLIENT
    value: dev-ops-it-2025
  - name: KEYCLOAK_SECRET
    valueFrom:
      secretKeyRef:
        name: dev-ops-it-2025
        key: keycloak_secret
  - name: KEYCLOAK_VERIFY
    value: "true"
  
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 200m
      memory: 200M

ingress:
  host: dev-ops-it-2025.boxed-bots.ru
