[tool.poetry]
name = "box-bot"
version = "1.0.0"
description = "Телеграм бот в коробочке для регистрации пользователей"
authors = ["Egor Dubrovin <dubrovinen@bmstu.ru>", "Daria Stepanova", "Ilya Reznikov", "Andrey Grishenko", "Sergey Kuznetsov", "Dmitry Radonezky"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "bot", from = "src" },
    { include = "ui", from = "src" },
    { include = "utils", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.12.2"
python-telegram-bot = {version = "^21.0.1", extras = ["job-queue"]}
python-dotenv = "^1.0.1"
pydantic = "^2.6.4"
pydantic-settings = "^2.2.1"
pyyaml = "^6.0.1"
loguru = "^0.7.2"
apscheduler = "^3.10.4"
jinja2 = "^3.1.3"
minio = "^7.2.5"
SQLAlchemy = "^2.0.28"
filetype = "^1.2.0"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
python-multipart = "^0.0.9"
oic = "^1.6.1"
PyJWT = "^2.8.0"
python-keycloak = "^3.9.1"
pillow = "^10.3.0"
pandas = "^2.2.2"
openpyxl = "^3.1.2"
XlsxWriter = "^3.2.0"
uuid = "^1.30"
asyncpg = "^0.30.0"
greenlet = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.uv.sources]
asyncpg = { git = "https://github.com/MagicStack/asyncpg"}