my_name:
  description: Название бота
  value: TwoBroWin | Бот в коробке

my_short_description:
  description: Краткое описание бота, показываемое при передаче ссылки на бота
  value: Я призван в мир, чтобы сделать работу с тг ботом удобной и наглядной

my_description:
  description: Описание бота, показываемое пользователю при начале взаимодействия с ботом
  value: |-
    Я - бот регистратор и координатор! Живу в коробочке и меня удобно настраивать!

    Помогу тебе зарегистрироваться, узнать всю нужную информацию и буду держать вкурсе обо всех изменениях!

help_command_description:
  description: Описание команды помощи
  value: Получить помощь

service_mode_message:
  description: Сообщение, отправляемые для всех пользователей если бот находится в сервисном режме
  value: |-
    👋 Привет! Я сейчас нахожусь на обслуживании, мои администраторы стараются как можно быстрее вернуть меня в строй 🫡

    ⌛ Подожди, пожалуйста, пару часов и введи /start чтобы начать или продолжить наше взаимодействие!

registration_is_over:
  description: Текст сообщения для пользователя в случае если регистрация уже заверешена
  value: |-
    👋 Привет! Спасибо что добрался до нас!
    
    К сожалению, регистрация уже закрыта...

    Не расстраивайся и держи жужу 🐝

start_template:
  description: |-
    Шаблон первого сообщения пользователю
    
    Используйте переменную {template} для того чтобы вывести в том же сообщении запрос первого поля от пользователя
  value: |-
    👋 Привет! Добро пожаловать!

    📝 Для регистрации мне понадобится информация о тебе.

    _Продолжая далее, Вы соглашаетесь на обработку персональных данных МГТУ им. Н.Э. Баумана_

    Введи следующие данные:

    {template}

first_field_branch:
  description: |-
    Ветка полей, с которой начинается взаимодействие с ботом

    *В качестве первого поля* берётся основное поле заданной ветки с наименьшим id
  value: Основные вопросы

user_document_name_field:
  description: Поле Пользователя, используемое как имя файлов
  value: ФИО

registration_complete:
  description: Текст сообщения, который будет показан пользователю когда он окончит регистрацию
  value: |-
    Спасибо за регистрацию! 😎

    Следи за обновлениями, сюда придут уведомления с дополнительными вопросами!

restart_user_template:
  description: |-
    Текст сообщения для пользователя в случае если он разбанил бота

    Это аналогично тому, что он попытался ввести команду /start снова, но он уже зарегистрирован
  value: |-
    👋 Привет! Добро пожаловать обратно!

    Напоминаю на чём мы с тобой остановились:

    {template}

help_user_template:
  description: |-
    Помощь обычному пользователю

    Других команд нет, все остальное см. на листе Клавиатура

    Для дальнейшего текст используйте переменную {template}
  value: |-
    👀 Помогаю тебе!

    {template}

help_restart_on_registration_complete:
  description: Текст второй части сообщения о возврате пользователя в случае если он уже зарегистрирован
  value: |-
    😉 Ты уже зарегистрирован

    ⌨ Сейчас я покажу тебе клавиатуру о чём можно меня спросить

user_change_message_reply_template:
  description: Шаблон подтверждения пользователю об изменении поля
  value: Значение *{state}* обновлено

strange_user_error:
  description: Текст ошибки, передаваемый пользователю в случае если он имеет доступ к боту, но не зарегистрирован
  value: |-
    👀 Странная ошибка, об этом сообщено администраторам

    Для регистрации введи команду /start

edited_message_reply:
  description: Ответ пользователю, который изменил одно из сообщений.
  value: |-
    Извини, но я не могу сохранить данные в изменённых сообщениях 😓

    Если надо обновить свои данные, то выбери пункт *👤 Управление регистрацией* после окончания регистрации

error_reply:
  description: Ответ пользователю об ошибке
  value: |-
    😢 Произошла ошибка, об этом уже сообщено администраторам

    Попробуй ещё раз

file_too_large_reply:
  description: Ответ пользователю об ошибке
  value: |-
    🐘 Слишком большой файл

    Пожалуйста, вышлите файл размером менее 20МБ

help_normal_group:
  description: Текст помощи для обычной группы пользователей
  value: |-
    Добро пожаловать в группу пользователей!

    Сюда будут приходить актуальные оповещения

help_admin_group:
  description: Текст помощи для группы администраторов
  value: |-
    Вы находитесь в группе *администраторов*

    В эту группу будут будут приходить отчёты при полной регистрации каждых 10 пользователей
    
    Введите команду /report для получения актуального отчёта по пользователям

    Сюда будут приходить копии оповещений пользователям

help_superadmin_group:
  description: Текст помощи для группы администраторов
  value: |-
    Вы находитесь в группе *супер администраторов*

    В эту группу будут будут приходить отчёты при полной регистрации каждых 10 пользователей
    
    Введите команду /report для получения актуального отчёта по пользователям

    Сюда будут приходить копии оповещений пользователям, а также уведомления об их планировании

notification_admin_groups_template:
  description: Шаблон оповещения групп админов о разосланных сообщениях
  value: |-
    _Данное сообщение только что было разослано всем пользователям:_

    {text_markdown}

notification_admin_groups_condition_template:
  description: Шаблон оповещения групп админов о разосланных сообщениях по условию
  value: |-
    _Данное сообщение только что было разослано пользователям согласно столбцу_ *{condition}*:

    {text_markdown}

notification_planned_admin_groups_template:
  description: Шаблон оповещения групп админов о разосланных сообщениях
  value: |-
    _Данное сообщение запланировано для рассылки всем пользователям в_ *{scheldue_date}*:

    {text_markdown}

notification_planned_admin_groups_condition_template:
  description: Шаблон оповещения групп админов о разосланных сообщениях по условию
  value: |-
    _Данное сообщение запланировано для рассылки всем пользователям согласно столбцу_ *{condition}* _в_ *{scheldue_date}*:

    {text_markdown}

report_send_every_x_active_users:
  description: Количество активных пользователей, по которым будет выслано оповещение в группу админов
  value: '10'

report_currently_active_users_template:
  description: Количество зерегистрированных активных пользователей для оперативного оповещения администраторов
  value: У нас уже *{count}* зарегистрированных активных пользователей

pass_user_field:
  description: Название ветки и пользовательского поля, содержащего пропуск
  value: Пропуск
user_field_to_request_pass:
  description: Необязательное по умолчанию поле, необходимое для получения пропуска
  value: Фото

pass_message:
  description: Сообщение, посылаемое вместе с пропуском пользователя
  value: Мы подготовили макет вашего пропуска. Электронную версию пропуска можно использовать в качестве подтверждения участия в программе лояльности!
pass_removed_message:
  description: Сообщение, высылаемое в случае если запланирована доставка сообщения с пропуском, но пропуска нет
  value: Вы можете оставить заявку на изготовление пропуска выпускника. Для этого необходимо выбрать пункт меню `Пропуск выпускника`.
pass_hint_message:
  description: Сообщение помощи пользователю о регистрации пропуска
  value: Вы можете оставить заявку на изготовление пропуска выпускника. Для этого необходимо загрузить фотографию и нажать на кнопку "Подать заявку на пропуск выпускника" под сообщением.
pass_add_field_to_request_value:
  description: Сообщение, отправляемое в случае если невозможно отправить запрос на формирование пропуска поскольку не заполнено поле, необходимое для получения пропуска
  value: Вам следует загрузить фотографию, вспользуйтесь кнопкой выше.

pass_not_yet_approved_message:
  description: Сообщение, посылаемое если пользователю ещё не выдан пропуск
  value: Ваша заявка принята и обрабатывается. Мы свяжемся с вами, когда все проверим!
pass_submit_message:
  description: Сообщение высылаемое пользователю при начале отправки заявки на пропуск
  value: Пожалуйста, подтвердите, что Вы согласны отправить заявку на получение пропуска
pass_submitted_message:
  description: Сообщение высылаемое пользователю после подтверждения отправки заявки на пропуск
  value: Ваша заявка отправлена, после обработки Вам будет выслано уведомление
pass_submited_superadmin_j2_template:
  description: Шаблон сообщения, отправляемого суперадминистраторам при отправке пользователем заявки на qr код
  value: |-
    Получена новая заявка на получение пропуска

    *ФИО*: `{% if 1 in fields %}{{ fields[1].value }}{% endif %}`

personal_notification_jinja_template:
  description: Шаблон сообщения, высылаемого как персональное уведомление для пользователя
  value: |-
    {%- if 'Промокод' in field.key or 'промокод' in field.key -%}
    Вам доступен *персональный* промокод:

    {% endif -%}
    *{{ field.key }}*: `{{ field.value }}`

expired_promocodes_jinja_template:
  description: Шаблон сообщения о просроченных промокодах
  value: |-
    Просрочены промокоды:

    {%- for promocode in promocodes %}
    *{{ promocode.source }}*: `{{ promocode.value }}`, был доступен до {{ promocode.expire_at }}
    {%- endfor -%}

avaliable_promocodes_jinja_template:
  description: Шаблон сообщения о доступных промокодах
  value: |-
    Доступные промокоды:

    {%- for promocode in promocodes %}
    {% if promocode.expire_at %}
    *{{ promocode.source }}*: `{{ promocode.value }}`, доступен до {{ promocode.expire_at.strftime('%d.%m.%Y') }}
    {%- else %}
    *{{ promocode.source }}*: `{{ promocode.value }}`
    {%- endif %}
    {% if promocode.description %}{{ promocode.description }}{% endif %}
    {%- endfor -%}
  
number_of_last_news_to_show:
  description: Количество последних показываемых новостей
  value: "5"
