
'no': Нет
'yes': Да
answer_options: Варианты ответа
append: Добавить
bot_is_off: Выключён
bot_is_on: Включён
bot_status: Статус бота
branch_id: Ветка
bucket: Бакет файлов
change: Изменить
chat_id: Id чата
check_future_date: Проверка корректности даты
check_future_year: Проверка корректности года
condition_bool_field_id: Условие показа/отправки
data_empty: Не заполнено
description: Описание
document_bucket: Бакет документа
document: Документ
done: Выполнено
download_file: Скачать
download_users_report: Полная выгрузка пользователей
error_answer_options_can_only_be_shown_with_full_text_field: Варианты ответа могут быть применены только для полнотекстового поля
error_bad_field_request: Некорректный запрос по полю
error_cannot_set_parent_key_id_in_keyboard_key_object_while_status_is_news: Невозможно задать родительскую кнопку для кнопки показа новостей
error_could_not_restore_previous_api_call: Не удалось восстановить данные предыдущего запроса - повторите ввод
error_could_not_update_bot_status: Не удалось обновить статус бота
error_could_not_update_settings: Не удалось обновить настройки
error_did_not_found_branch_id_in_keyboard_key_object_while_status_is_me: Не найдено ветки вопросов для клавиши показа пользователя
error_did_not_found_parent_key_id_in_keyboard_key_object_while_status_is_back: Не нейдено родительской кнопки для кнопки вернуться выше
error_did_not_found_reply_answer_field_branch_id_in_replyable_condition_message_object_while_status_is_branch_start: Не указана ветка ответов для ответа с типом начала ветки
error_did_not_found_reply_answer_field_id_in_replyable_condition_message_object_while_status_is_full_text_answer_or_fast_answer: Не указано поле ответа для полнотекстового ответа или быстрого ответа
error_did_not_found_reply_condition_message_id_in_keyboard_key_object_while_status_is_normal: Не найдено сообщение с условием и ответом для обычной кнопки клавиатуры
error_did_not_update_table: Не удалось обновить запись
error_field_id_was_not_found: Не нейдено поле с идентификатором
error_field_is_not_in_request: В запросе нет поля
error_field_prefix: Поле
error_field_with_bucket_must_have_document_or_image_type: Поле с бакетом должно иметь тип изображения или документа
error_field_with_document_or_image_type_must_have_bucket: Поле с типом изображения или документа должен иметь бакет
error_field_with_validation_regexp_should_be_full_text_type: Поле с регулярным выражением должно иметь полнотекстовый тип
error_field_with_validation_remove_regexp_should_be_full_text_type: Поле с регулярным выражением удаления должно иметь полнотекстовый тип
error_for_jinja2_field_must_not_be_set_is_skippable_check_future_date_check_future_year_upper_before_save_params: Вычисляемое Jinja2 поле не может быть пропускаемым, иметь прверку будущей даты или будущего года
error_found_photo_link_in_replyable_condition_message_while_photo_bucket_or_photo_filename_are_also_in_replyable_condition_message: Невозможно задать одновременно ссылку на изображение и бакет и файл изображения
error_found_unknown_bot_status: Неизвестный статус бота
error_found_unknown_request_field: Получено неизвестное поле
error_got_bad_id: Некорректный идентификатор
error_got_bad_key_value_pair: Получено некорректная пара ключ-значение
error_got_bad_user_fields: Получены некорректные поля пользователя
error_got_not_numeric_field_id: Получен нечисловой идентификатор поля
error_got_not_numeric_user_id: Получен нечисловой идентификатор пользователя
error_got_value_error_as: Ошибка типа поля
error_group_prefix: Группа
error_jinja2_field_should_be_full_text_or_boolean: Вычисляемое Jinja2 поле должно иметь полнотекстовый или булев тип
error_keyboard_key_prefix: Кнопка клавиатуры
error_logout_not_by_get_method_it_mus_be_impossible: Выполнен выход при помощи другого метода, нежели GET, это должно быть невозможно
error_minio_no_bio: В хранилище не найден файл
error_new_lines_found_in_reply_keyboard_keys_in_replyable_condition_message_object_while_status_is_full_text_answer_or_branch_start: Должна быть задана только одна строка для полнотекстового ответа или начала ветки вопросов
error_no_name_or_text_markdown_in_replyable_condition_message: Нет названия или текста Markdown
error_reply_type_is_set_but_there_is_no_reply_keyboard_keys_or_reply_status_replies: Указан тип сообщения с ответом, но не указаны клавиши ответа или ответ на окончание взаимодействия с пользователем
error_replyable_condition_message_prefix: Сообщение с условием и ответом
error_should_be_numeric_but_got: должно быть целочисленным, но получено
error_should_set_both_photo_bucket_and_photo_filename_at_the_same_time: Следует одновременно задать бакет и файл изображения
error_there_is_no_field_branches: Нет веток полей
error_trying_to_set_pass_managment_to_non_admin_group: Группа, имеющая права управления пропусками, должна быть группой админимтраторов или суперадминистраторов
error_value_not_directory_field_value: Значение поля не является словарём
error_value_not_in_field_value: Нет значения поля
expire_at: Дата окончания действия
field_branch_inactive: Не активна
field_branch_normal: Активна
field_branches: Ветки полей
field_inactive: Не активен
field_jinja2_from_user_after_registration: Вычисляемое Jinja2 после окончания регистрации
field_jinja2_from_user_on_create: Вычисляемое Jinja2 при создании пользователя
field_normal: Активен
field_personal_notifiation: С уведомлением о значении
field_type_boolean: Булево поле
field_type_full_text: Полнотекстовое поле
field_type_image: Изображение
field_type_pdf_document: PDF документ
field_type_zip_document: ZIP архив
fields: Поля пользователей
group_admin: Админы
group_inactive: Не активна
group_news_channel: Новостной канал
group_normal: Обычная
group_super_admin: Супер админы
groups: Группы
image_bucket: Бакет изображений
image: Изображение
is_active: Регистрация активна
is_boolean: Булево
is_bot_editable: Можно менять в боте
is_deferrable: Можно отложить
is_inactive: Регистрация не активна
is_registration_open: Статус регистрации
is_skippable: Можно пропустить
is_ui_editable: Можно менять в UI
key: Ключ
keyboard_key_back: Вернуться к меню выше
keyboard_key_deferred: Отложенные вопросы
keyboard_key_inactive: Не активна
keyboard_key_me_change: Изменение профиля
keyboard_key_me: Профиль
keyboard_key_news: Новости
keyboard_key_normal: Обычная кнопка
keyboard_key_pass: Показать пропуск
keyboard_key_promocodes: Промокоды
keyboard_keys: Клавиатура
keyboard: Клавиатура
logout: Выйти
logs: Логи
message: Сообщение
new_record: Новая запись
news_tag: Тег новостей
next_branch_id: Следующая ветка
none: Пусто
notification_delivered: ✅ Отправлено
notification_inactive: ❌ Не активно
notification_planned: 🔷 Запланировано
notification_to_deliver: 🟠 Отправить
notifications: Оповещения
order_place: Порядок
parent_key_id: Родительская кнопка
pass_management: Управление пропусками
pass_status_after_receiving: Статус пропуска после получения сообщения
pass_status_approved: Пропуск согласован
pass_status_not_submited: Пропуск не запрошен
pass_status_submited: Пропуск запрошен
personal_notification_delivered: ✅ Доставлено
personal_notification_inactive: ❌ Не активно
personal_notification_to_deliver: 🔷 Запланирована доставка
photo_bucket: Бакет изображения
photo_filename: Файл изображения
photo_link: Ссылка на изображение
promocode_active: ✅ Активен
promocode_expired: ⌛ Просрочен
promocode_inactive: ❌ Не активен
promocodes: Промокоды
question_markdown_or_j2_template: Вопрос Markdown или Шаблон Jinja2
register: Управление регистрацией
registration_close: Закрыть регистрацию
registration_closed: Закрыта
registration_open: Открыть регистрацию
registration_opened: Открыта
registration_set_active: Регистрация активирована
registration_set_inactive: Регистрация деактивирована
registration: Параметры регистрации
reply_answer_field_branch_id: Ветка вопросов
reply_answer_field_id: Вопрос
reply_condition_bool_field_id: Условие ответа
reply_condition_message_id: Сообщение
reply_condition_message_name: Обозначение
reply_keyboard_keys: Клавиши
reply_status_replies: Ответы/Следующие вопросы
reply_type_branch_start: Ветка вопросов
reply_type_fast_answer_with_next: Один вопрос и переход
reply_type_fast_answer: Быстрый ответ
reply_type_full_text_answer: Один вопрос
reply_type_pass: Клавиатура пропуска
reply_type: Тип ответа
replyable_condition_messages: Сообщения с условиями и ответами
report_order: Номер в отчёте пропусков
report: Отчет
restart_normal: Перезапустить в нормальный режим
restart_planned: Назначен перезапуск
restart_service: Перезапустить в сервисный режим
restarting: Перезапускается
schedule_datetime: Дата уведомления
service_mode: Сервисный режим
set_active: Вернуть регистрацию
set_inactive: Отменить регистрацию
settings: Настройки
source: Источник
status: Статус
super: Супер
text_markdown: Тест разметки markdwon
there_was_en_error: Произошла ошибка!
timestamp: Метка времени
turn_off: Выключить
turn_on: Включить
type_error_markdown: Сообщение ошибки типа
type: Тип
upper_before_save: Преобразовать в верхний регистр
username: Имя пользователя Телеграм
users: Пользователи
validation_error_markdown: Ошибка Markdown
validation_regexp: Регулярное выражение валидации
validation_remove_regexp: Регулярное выражение удаления
value: Значение