apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.uiContainer.containerPort }}
  selector:
    app: {{ .Release.Name }}-ui
