---
#############################################################################
# 0) Взять секреты из vault и добавить SSH ключи в known_hosts              #
#############################################################################

- name: Pull secrets from vault
  hosts: obtain_certs
  gather_facts: false
  tags:
    - always
  roles:
    - role: bmstu.vats.init

#############################################################################
# 1) Разместить на машине скрипт для копирования сертификатов в по сервисам #
#############################################################################

- name: Template copy services certs hook
  hosts: obtain_certs
  tags:
    - always
  become: true
  tasks:
    - name: Create letsencrypt hooks directory
      file:
        path: "{{ letsencrypt_post_hook_pathes }}"
        state: directory
    
    - name: Template copy services certs hook
      template:
        src:  ../scripts/copy-services-certs.j2.sh
        dest: "{{ letsencrypt_copy_services_certs }}"
        mode: u=rwx,g=rx

#############################################################################
# 2a) Получение сертификатов с настройкой автоматического обновления        #
#############################################################################

- hosts: obtain_certs
  tags:
    - obtain_certs
  become: true
  vars:
    certbot_install_method:    package
    certbot_auto_renew:        yes
    certbot_auto_renew_user:   "root"
    certbot_auto_renew_hour:   "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet"
    certbot_create_if_missing: yes
    certbot_create_method:     "standalone"
    certbot_hsts:              yes
    certbot_admin_email:       "{{ secrets.admin_email }}"
    certbot_testmode:          no
    certbot_certs:
      - domains:
          - "{{ secrets.server_name }}"
    certbot_create_standalone_stop_services:
      - docker
    certbot_create_extra_args: "--deploy-hook {{ letsencrypt_copy_services_certs }}"
  roles:
    - geerlingguy.certbot

#############################################################################
# 2б) Сгенерировать сертификаты                                             #
#############################################################################

- hosts: obtain_certs
  tags:
    - generate_certs
  become: true
  vars:
    country_name: RU
    organization_name: BMSTU
  tasks:
    - name: Create certs dir
      file:
        path: "{{ certs_base_path }}"
        state: directory

    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "{{ certs.privkey_path }}"
        size: 4096
        type: RSA
        backup: yes

    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "{{ certs.csr_path }}"
        privatekey_path: "{{ certs.privkey_path }}"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ secrets.admin_email }}"
        common_name: "{{ secrets.server_name }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "{{ certs.fullchain_path }}"
        privatekey_path: "{{ certs.privkey_path }}"
        csr_path: "{{ certs.csr_path }}"
        provider: selfsigned
    
    - name: Run post generate hook - copy services certs
      shell: "{{ letsencrypt_copy_services_certs }}"
